---
apiVersion: v1
kind: Secret
metadata:
  name: hugo-test-project-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-aro24/hugo-test-project-gateway-gitops
